### ISSUE TITLE
error when use lib with electron

### ISSUE THREAD

**Issue by igorcandeia** [santigimeno/node-pcsclite#61]
App threw an error during load
Error: Cannot find module './build/Debug/buffertools.node'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\Igor\electron-quick-start\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Igor\electron-quick-start\node_modules\buffertools\buffertools.js:26:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by santigimeno** [comment]
It's not a pcsclite issue.
See this: http://electron.atom.io/docs/tutorial/using-native-node-modules/
You should rebuild the native modules using `electron-rebuild`.

I'm closing this for the moment. Re-open if you think it's still an issue. Thanks
