### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by barisvelioglu** [santigimeno/node-pcsclite#64]
When I run the `npm install pcsclite`, it doesnt work

```
> buffertools@2.1.4 install /home/barisvelioglu/Projects/test/node_modules/buffertools
> node-gyp rebuild

make: Entering directory '/home/barisvelioglu/Projects/test/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/obj.target/buffertools.node
  COPY Release/buffertools.node
make: Leaving directory '/home/barisvelioglu/Projects/test/node_modules/buffertools/build'

> pcsclite@0.4.11 install /home/barisvelioglu/Projects/test/node_modules/pcsclite
> node-gyp rebuild

make: Entering directory '/home/barisvelioglu/Projects/test/node_modules/pcsclite/build'
  CXX(target) Release/obj.target/pcsclite/src/addon.o
In file included from ../src/addon.cpp:1:0:
../src/pcsclite.h:9:22: fatal error: winscard.h: No such file or directory
compilation terminated.
pcsclite.target.mk:112: recipe for target 'Release/obj.target/pcsclite/src/addon.o' failed
make: *** [Release/obj.target/pcsclite/src/addon.o] Error 1
make: Leaving directory '/home/barisvelioglu/Projects/test/node_modules/pcsclite/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/barisvelioglu/Projects/test/node_modules/pcsclite
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pcsclite"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pcsclite@0.4.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcsclite@0.4.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcsclite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcsclite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcsclite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/barisvelioglu/Projects/test/npm-debug.log

```

**Comment by santigimeno** [comment]
It looks like you don't have `libpcsclite-dev` package installed
